.PHONY: run build-windows build-linux clean

# Run the application locally
run:
	uv run ./main.py

# Build for Windows (Must be run on a Windows machine)
# Note: Windows uses a semicolon ';' separator for --add-data
build-windows:
	uv run pyinstaller --name "StaffDocx" --noconsole --onefile --windowed --add-data "assets;assets" --icon="assets/app_icon.png" main.py

# Build for Linux (Can be run on your current machine)
# Note: Linux uses a colon ':' separator for --add-data
build-linux:
	uv run pyinstaller --name "StaffDocx" --noconsole --onefile --windowed --add-data "assets:assets" --icon="assets/app_icon.png" main.py

# Clean up build artifacts generated by PyInstaller
clean:
	rm -rf build/ dist/ StaffDocx.spec
